sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) #SHA from the commit and apply it to git images that we upload
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #disable and promts for google cloud CLI
before_install:
  #configure google cloud account configuration
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project <project_name> #this to be used to configure google cloud cli
  - gcloud config set compute/zone us-central1-a #this to be used to configure google cloud cli
  - gcloud container clusters get-credentials multi-cluster #this to be used to configure google cloud cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #env variables defined in TravisCI
  - docker build -t USERNAME/react-test -f ./client/Dockerfile.de ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master